#define TOKEN_PROGRAM 1
#define TOKEN_IF 2
#define TOKEN_THEN 3 
#define TOKEN_END 4
#define TOKEN_ELSE 5
#define TOKEN_REPEAT 6
#define TOKEN_UNTIL 7
#define TOKEN_WHILE 8
#define TOKEN_DO 9
#define TOKEN_READ 10
#define TOKEN_WRITE 11
#define TOKEN_IN 12
#define TOKEN_FLOAT 13
#define TOKEN_INTEGER 14
#define TOKEN_CHARACTER 15
#define TOKEN_LITERAL 16
#define TOKEN_IDENTIFIER 17
#define TOKEN_IS 18
#define TOKEN_BEGIN 19
#define TOKEN_COMMENT 20
#define TOKEN_NUMBER 21
#define TOKEN_AND 'a'
#define TOKEN_OR 'o'
#define TOKEN_EQUALS 'e'
#define TOKEN_GREATER '>'
#define TOKEN_GREATER_THAN_EQUALS 'g'
#define TOKEN_LESSER '<'
#define TOKEN_LESSER_THAN_EQUALS 'l'
#define TOKEN_DIFFERENT '!'
#define TOKEN_SUM '+'
#define TOKEN_MINUS '-'
#define TOKEN_MULTIPLY '*'
#define TOKEN_QUOTIENT '/'
#define TOKEN_ASSIGN '='
#define TOKEN_SEMICOLON ';'
#define TOKEN_COMMA ','
#define TOKEN_LPAREN '('
#define TOKEN_RPAREN ')'
#define TOKEN_NEGATIVE '!'